version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: krocker33
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: krocker3
      MYSQL_PASSWORD: krocker33
    volumes:
    - mysql_data_container:/data/db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: krocker1
      MONGO_INITDB_ROOT_PASSWORD: krocker33
    ports:
      - 27017:27017
    volumes:
    - mongo_data_container:/data/db
volumes:
  mysql_data_container:
  mongo_data_container: